on:
  push:
  pull_request:
  schedule:
  - cron: '0 0 * * *' # test daily against git HEAD of dependencies

name: CI
jobs:

  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version:
        - '3.8'
        # this version range needs to be synchronized with the one in pyproject.toml
        amaranth-version:
        - 'git'
      fail-fast: false
    steps:
      - name: Check out source code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Set up PDM
        uses: pdm-project/setup-pdm@v3
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          pip install codecov
          pdm install --dev
      - name: Install Amaranth release
        if: ${{ matrix.amaranth-version != 'git' }}
        run: |
          pip install 'amaranth==${{ matrix.amaranth-version }}'
      - name: Install Amaranth from git
        if: ${{ matrix.amaranth-version == 'git' }}
        run: |
          pip install git+https://github.com/amaranth-lang/amaranth.git
      - name: Run tests
        run: |
          pdm run test
      - name: Submit code coverage
        run:
          codecov

  required: # group all required workflows into one for the required status check
    needs:
      - test
    runs-on: ubuntu-latest
    steps:
      - run: |
          true
